name: .NET Core CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: [self-hosted, windows, ltvm10]

    steps:
      - name: Extract Source Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Initialize .NET SDK 8.0
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet Dependencies
        run: dotnet restore .\unit-testing-using-dotnet-test.sln
        shell: powershell

      - name: Build Application Structure
        run: dotnet build .\unit-testing-using-dotnet-test.sln --configuration Release --no-restore
        shell: powershell

      - name: Execute Unit Tests
        run: dotnet test .\unit-testing-using-dotnet-test.sln --configuration Release --no-build --verbosity normal
        shell: powershell
