name: .NET Core CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: [self-hosted, windows, ltvm10]

    steps:
      - name: Extract Source Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Initialize .NET SDK 8.0
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet Dependencies
        run: dotnet restore .\unit-testing-using-dotnet-test.sln
        shell: powershell

      - name: Build Application Structure
        run: dotnet build .\unit-testing-using-dotnet-test.sln --configuration Release --no-restore
        shell: powershell

      - name: Execute Unit Tests
        run: dotnet test .\unit-testing-using-dotnet-test.sln --configuration Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=".\TestResults\coverage.opencover.xml"
        shell: powershell

      - name: Persist Application Binary Package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: application-package
          path: |
            **/bin/Release/**/*.dll
            **/bin/Release/**/*.exe
          retention-days: 5

      - name: Persist OpenCover Metrics XML Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: opencover-report
          path: .\TestResults\coverage.opencover.xml
          retention-days: 5

  package-and-release:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: [self-hosted, windows, ltvm10]

    steps:
      - name: Extract Source Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Initialize .NET SDK 8.0
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
        with:
          dotnet-version: '8.0.x'

      - name: Create Production NuGet/App Package
        run: dotnet pack --configuration Release --output .\artifacts
        shell: powershell
